import { auth, db } from "./firebase.js";
import {
  addDoc,
  collection,
  doc,
  getDoc,
  onSnapshot,
  query,
  serverTimestamp,
  updateDoc,
  where
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const REPORT_PREFIX = "SSA-RPT";

function makeReportId() {
  const stamp = new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0, 14);
  const random = Math.random().toString(36).slice(2, 7).toUpperCase();
  return `${REPORT_PREFIX}-${stamp}-${random}`;
}

export async function submitReport({
  title,
  description,
  category = "general",
  type = "platform",
  priority = "medium",
  reportedUserId = null,
  reportedUserName = null,
  courseId = null,
  courseName = null,
  metadata = {}
}) {
  const user = auth.currentUser;
  if (!user) throw new Error("You must be signed in to submit a report.");
  if (!title?.trim() || !description?.trim()) throw new Error("Report title and description are required.");

  const reportId = makeReportId();
  const ref = await addDoc(collection(db, "reports"), {
    reportId,
    title: title.trim(),
    description: description.trim(),
    category,
    type,
    priority,
    status: "pending",
    reporterId: user.uid,
    reporterName: user.displayName || null,
    reporterEmail: user.email || null,
    reportedUserId,
    reportedUserName,
    courseId,
    courseName,
    metadata,
    moderatorNotes: "",
    feedback: "",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });

  // Notifications are generated by the trusted Firebase Function trigger.
  return { id: ref.id, reportId };
}

export async function getReport(reportId) {
  if (!reportId) return null;
  const snapshot = await getDoc(doc(db, "reports", reportId));
  return snapshot.exists() ? { id: snapshot.id, ...snapshot.data() } : null;
}

export function subscribeToMyReports(userId, callback) {
  if (!userId) return () => {};
  const reportsQuery = query(collection(db, "reports"), where("reporterId", "==", userId));
  return onSnapshot(reportsQuery, snapshot => {
    const reports = snapshot.docs
      .map(item => ({ id: item.id, ...item.data() }))
      .sort((a, b) => timestamp(b.updatedAt || b.createdAt) - timestamp(a.updatedAt || a.createdAt));
    callback(reports);
  });
}

export async function reviewReport({
  reportId,
  status,
  feedback = "",
  moderatorNotes = "",
  reviewedBy = null
}) {
  if (!reportId) throw new Error("reportId is required.");
  const user = auth.currentUser;
  if (!user) throw new Error("You must be signed in.");

  const reportRef = doc(db, "reports", reportId);
  const snapshot = await getDoc(reportRef);
  if (!snapshot.exists()) throw new Error("Report not found.");

  const finalStatus = ["pending", "reviewing", "resolved", "dismissed", "closed"].includes(status) ? status : "reviewing";
  await updateDoc(reportRef, {
    status: finalStatus,
    feedback: feedback.trim(),
    moderatorNotes: moderatorNotes.trim(),
    reviewedBy: reviewedBy || user.uid,
    reviewedAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });

  // Reporter feedback notification is generated by the trusted backend trigger.
  return getReport(reportId);
}

function timestamp(value) {
  if (!value) return 0;
  if (typeof value.toMillis === "function") return value.toMillis();
  if (typeof value.toDate === "function") return value.toDate().getTime();
  return new Date(value).getTime() || 0;
}
