import {auth,db} from "../../js/firebase.js";
import {onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {collection,query,orderBy,onSnapshot,doc,updateDoc,addDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const $=id=>document.getElementById(id);let rows=[];let me=null;
const money=n=>`KES ${Number(n||0).toLocaleString("en-KE",{minimumFractionDigits:2})}`;
const date=v=>{if(!v)return "—";try{return (v.toDate?v.toDate():new Date(v)).toLocaleString("en-KE")}catch{return "—"}};
function toast(m){const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}
function render(){const term=$("payoutSearch").value.trim().toLowerCase(),filter=$("payoutStatus").value;const data=rows.filter(x=>(filter==="all"||String(x.status||"pending").toLowerCase()===filter)&&(!term||JSON.stringify(x).toLowerCase().includes(term)));const totals={pending:[0,0],approved:[0,0],paid:[0,0],rejected:[0,0]};rows.forEach(x=>{const s=String(x.status||"pending").toLowerCase();if(totals[s]){totals[s][0]+=Number(x.amount||0);totals[s][1]++}});["pending","approved","paid","rejected"].forEach(s=>{$(`${s}Amount`).textContent=money(totals[s][0]);$(`${s}Count`).textContent=`${totals[s][1]} ${s==='paid'?'payouts':'requests'}`});$("payoutTable").innerHTML=data.length?data.map(x=>`<tr><td><strong>${x.instructorName||x.name||"Unknown instructor"}</strong><br><small>${x.instructorId||x.userId||x.id}</small></td><td>${money(x.amount)}</td><td>${x.method||x.paymentMethod||"M-PESA"}</td><td>${date(x.createdAt||x.requestedAt)}</td><td><span class="status ${String(x.status||"pending").toLowerCase()}">${x.status||"pending"}</span></td><td><div class="actions">${String(x.status||"pending").toLowerCase()==="pending"?`<button class="action" data-a="approve" data-id="${x.id}">Approve</button><button class="action" data-a="reject" data-id="${x.id}">Reject</button>`:String(x.status||"").toLowerCase()==="approved"?`<button class="action" data-a="paid" data-id="${x.id}">Mark paid</button>`:`<button class="action" data-a="view" data-id="${x.id}">View</button>`}</div></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No payout requests found.</td></tr>`}
async function action(id,a){const ref=doc(db,"payouts",id);if(a==="view")return toast("Payout record loaded.");const status=a==="approve"?"approved":a==="reject"?"rejected":"paid";await updateDoc(ref,{status,reviewedBy:me.uid,reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});await addDoc(collection(db,"auditLogs"),{action:`payout_${status}`,targetId:id,actorId:me.uid,createdAt:serverTimestamp()});toast(`Payout ${status}.`)}
function watch(){const q=query(collection(db,"payouts"),orderBy("createdAt","desc"));onSnapshot(q,s=>{rows=s.docs.map(d=>({id:d.id,...d.data()}));render()},e=>{console.error(e);toast("Unable to load payouts.")})}
$("payoutSearch").addEventListener("input",render);$("payoutStatus").addEventListener("change",render);$("refreshPayouts").onclick=()=>render();$("payoutTable").addEventListener("click",e=>{const b=e.target.closest("button[data-a]");if(b)action(b.dataset.id,b.dataset.a).catch(err=>{console.error(err);toast("Payout action failed.")})});
onAuthStateChanged(auth,u=>{if(!u){location.href="../../login.html";return}me=u;watch()});
