import {auth,db} from "../../js/firebase.js";
import {onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {collection,doc,getDoc,getDocs,setDoc,updateDoc,addDoc,query,orderBy,onSnapshot,serverTimestamp} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const $=id=>document.getElementById(id);let user=null,wallets=[],transactions=[];
const money=n=>`KES ${Number(n||0).toLocaleString("en-KE",{minimumFractionDigits:2})}`;
const date=v=>{if(!v)return "—";try{return (v.toDate?v.toDate():new Date(v)).toLocaleString("en-KE")}catch{return "—"}};
function toast(m,type="ok"){const x=document.createElement("div");x.className=`wallet-toast ${type}`;x.textContent=m;document.body.appendChild(x);requestAnimationFrame(()=>x.classList.add("show"));setTimeout(()=>x.remove(),2800)}
async function founderGuard(u){const s=await getDoc(doc(db,"users",u.uid));if(!s.exists()||!["founder","super_admin"].includes(s.data().role)){toast("Founder access required","error");return false}return true}
async function treasury(){const ref=doc(db,"finance","treasury"),s=await getDoc(ref);if(!s.exists()){await setDoc(ref,{balance:0,reservedFunds:0,monthlyRevenue:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return {balance:0,reservedFunds:0,monthlyRevenue:0}}return s.data()}
function renderTreasury(t){["treasuryBalance","treasuryAvailable"].forEach(id=>$(id)&&($(id).textContent=money(t.balance)));if($("founderBalance"))$("founderBalance").textContent=money(t.founderBalance||0);if($("reservedFunds"))$("reservedFunds").textContent=money(t.reservedFunds);if($("monthlyRevenue"))$("monthlyRevenue").textContent=money(t.monthlyRevenue);if($("pendingWithdrawals"))$("pendingWithdrawals").textContent=money(t.pendingWithdrawals||0);if($("lastReconciliation"))$("lastReconciliation").textContent=date(t.updatedAt)}
async function loadWallets(){const s=await getDocs(collection(db,"instructorWallets"));wallets=s.docs.map(d=>({id:d.id,...d.data()}));const total=wallets.reduce((a,w)=>a+Number(w.balance||0),0);if($("instructorBalance"))$("instructorBalance").textContent=money(total);renderWallets()}
function renderWallets(){const el=$("instructorWalletTable")||$("walletTable");if(!el)return;const term=($("walletSearch")?.value||"").toLowerCase();const filter=$("walletFilter")?.value||"all";const list=wallets.filter(w=>(filter==="all"||String(w.status||"active").toLowerCase()===filter||(filter==="empty"&&!Number(w.balance)))&&(!term||`${w.name||""} ${w.instructorId||""} ${w.walletId||w.id}`.toLowerCase().includes(term)));el.innerHTML=list.length?list.map(w=>`<tr><td><strong>${w.name||"Unknown"}</strong></td><td>${w.instructorId||"—"}</td><td>${w.walletId||w.id}</td><td>${money(w.balance)}</td><td><span class="status ${w.status||"active"}">${w.status||"active"}</span></td><td>${date(w.updatedAt||w.createdAt)}</td><td><button class="secondary-btn manage-wallet" data-id="${w.id}">Manage</button></td></tr>`).join(""): `<tr><td colspan="7" class="empty-table">No instructor wallets found.</td></tr>`}
async function loadTransactions(){try{const q=query(collection(db,"financeTransactions"),orderBy("createdAt","desc"));const s=await getDocs(q);transactions=s.docs.map(d=>({id:d.id,...d.data()}));renderTransactions()}catch(e){console.warn("Transaction ledger unavailable",e.message)}}
function renderTransactions(){const el=$("transactionHistoryTable");if(!el)return;el.innerHTML=transactions.slice(0,100).map(x=>`<tr><td>${x.id}</td><td>${x.type||"—"}</td><td>${x.from||"—"}</td><td>${x.to||"—"}</td><td>${money(x.amount)}</td><td><span class="status ${x.status||"completed"}">${x.status||"completed"}</span></td><td>${x.approvedBy||"Founder"}</td><td>${date(x.createdAt)}</td><td>—</td></tr>`).join("")||`<tr><td colspan="9" class="empty-table">No financial transactions found.</td></tr>`}
async function openWallet(id){const w=wallets.find(x=>x.id===id);if(!w)return;const action=prompt(`Wallet: ${w.name||w.id}\nEnter action: credit, debit, freeze, unfreeze`);if(!action)return;if(["freeze","unfreeze"].includes(action)){await updateDoc(doc(db,"instructorWallets",id),{status:action==="freeze"?"frozen":"active",updatedAt:serverTimestamp()});toast(`Wallet ${action}d`);await loadWallets();return}const amount=Number(prompt("Amount in KES"));if(!Number.isFinite(amount)||amount<=0)return toast("Invalid amount","error");if(action==="debit"&&Number(w.balance||0)<amount)return toast("Insufficient wallet balance","error");const next=action==="credit"?Number(w.balance||0)+amount:Number(w.balance||0)-amount;await updateDoc(doc(db,"instructorWallets",id),{balance:next,updatedAt:serverTimestamp()});await addDoc(collection(db,"financeTransactions"),{type:action,from:action==="debit"?id:"academy",to:action==="credit"?id:"academy",amount,status:"completed",approvedBy:user.uid,createdAt:serverTimestamp()});toast(`Wallet ${action}ed`);await loadWallets();await loadTransactions()}
function exportData(){const csv=["ID,Type,Amount,Status,Date",...transactions.map(x=>`${x.id},${x.type||""},${x.amount||0},${x.status||""},"${date(x.createdAt)}"`)].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="ssa-financial-ledger.csv";a.click()}
async function boot(){const t=await treasury();renderTreasury(t);await Promise.all([loadWallets(),loadTransactions()]);$("walletSearch")?.addEventListener("input",renderWallets);$("walletFilter")?.addEventListener("change",renderWallets);$("refreshFinance")?.addEventListener("click",boot);$("refreshWallets")?.addEventListener("click",boot);$("exportLedger")?.addEventListener("click",exportData);$("exportFinance")?.addEventListener("click",exportData);$("instructorWalletTable")?.addEventListener("click",e=>{const b=e.target.closest(".manage-wallet");if(b)openWallet(b.dataset.id).catch(x=>{console.error(x);toast("Wallet action failed","error")})});$("backupWallets")?.addEventListener("click",()=>toast("Finance backup should be handled by your backend/Supabase job."));$("reconcileAccounts")?.addEventListener("click",async()=>{const ref=doc(db,"finance","treasury");await updateDoc(ref,{updatedAt:serverTimestamp()});toast("Treasury reconciliation timestamp updated")})}
onAuthStateChanged(auth,async u=>{if(!u){location.href="../../login.html";return}user=u;if(await founderGuard(u))await boot()});